### ISSUE TITLE
Update script does not push the tags / releases.

### ISSUE THREAD

**Issue by JeroenKnoops** [rajbos/github-fork-updater#12]
I'm using the github-fork-updater, but it does not seem to sync the releases / tags.

### Upstream
Tags: https://github.com/blackducksoftware/github-action/tags
Releases: https://github.com/blackducksoftware/github-action/releases

Tag v2.2: https://github.com/blackducksoftware/github-action/releases/tag/v2.2
Release v2.2: https://github.com/blackducksoftware/github-action/releases/tag/v2.2

### Update
https://github.com/philips-forks/github-fork-updater/issues/18
https://github.com/philips-forks/github-fork-updater/runs/4162686987?check_suite_focus=true

### Downstream after update
Tags: https://github.com/philips-forks/blackduck-github-action/tags
Releases: https://github.com/philips-forks/blackduck-github-action/releases

No v2.2

## See also
https://github.com/asml-actions/github-fork-updater/issues/4

**Comment by rajbos** [comment]
Thanks for the feedback! I thought I already had an issue for this but apparently not yet :-D.

This should be as straightforward as updating the `git push` call to include all the tags as well. Do be aware that the releases for actions come from the tags, so a formal release is not needed (ASFAIK). I also don't know of a way to include those at all, since they don't come over for a fork.

Will see if I can add the pushing of tags soon.

**Comment by rajbos** [comment]
Awesome! Will merge that in!
